# Generated by Django 5.2.4 on 2025-07-25 21:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Motorcycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
                ('production_year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(2025)])),
                ('engine_type', models.CharField(choices=[('Inline', 'Inline'), ('V', 'V')], max_length=20)),
                ('engine_volume', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('engine_power', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
    ]
