# Generated by Django 5.2.4 on 2025-08-02 10:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorcycles', '0002_motoaccessories'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotorcycleAccessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('make', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
            ],
            options={
                'verbose_name_plural': 'Motorcycle Accessories',
            },
        ),
        migrations.CreateModel(
            name='MotorcycleParts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('make', models.CharField(max_length=20)),
                ('category', models.CharField(choices=[('Engine', 'Engine'), ('Chain Drive', 'Chain Drive'), ('Suspension', 'Suspension'), ('Brakes', 'Brakes'), ('Exhaust', 'Exhaust'), ('Electric', 'Electric'), ('Fairings', 'Fairings'), ('Tyres', 'Tyres'), ('Other', 'Other')], default='Other', max_length=20)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
            ],
            options={
                'verbose_name_plural': 'Motorcycle Parts',
            },
        ),
        migrations.DeleteModel(
            name='MotoAccessories',
        ),
        migrations.AddField(
            model_name='motorcycle',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='motorcycle',
            name='type',
            field=models.CharField(choices=[('Sport', 'Sport'), ('Touring', 'Touring'), ('Cruiser', 'Cruiser'), ('Off-Road', 'Off-Road'), ('Other', 'Other')], default='Other', max_length=10),
        ),
        migrations.AlterField(
            model_name='motorcycle',
            name='engine_power',
            field=models.PositiveSmallIntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='motorcycle',
            name='engine_type',
            field=models.CharField(choices=[('Inline', 'Inline'), ('V', 'V'), ('Other', 'Other')], default='Other', max_length=20),
        ),
        migrations.AlterField(
            model_name='motorcycle',
            name='engine_volume',
            field=models.PositiveSmallIntegerField(default=1000, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2200)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='motorcycleparts',
            name='compatible_motorcycles',
            field=models.ManyToManyField(blank=True, to='motorcycles.motorcycle'),
        ),
    ]
