# Generated by Django 5.2.4 on 2025-08-02 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorcycles', '0003_motorcycleaccessories_motorcycleparts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorcycle',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='motorcycleaccessories',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='motorcycleparts',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
