# Generated by Django 5.2.4 on 2025-08-03 14:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorcycles', '0004_motorcycle_image_url_motorcycleaccessories_image_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='motorcycle',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='motorcycleaccessories',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Motorcycle Accessories'},
        ),
        migrations.AlterModelOptions(
            name='motorcycleparts',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Motorcycle Parts'},
        ),
        migrations.AddField(
            model_name='motorcycle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='motorcycle',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='motorcycleaccessories',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='motorcycleaccessories',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='motorcycleparts',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='motorcycleparts',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
