# Generated by Django 5.2.4 on 2025-08-03 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=30)),
                ('specialization', models.CharField(choices=[('Electric', 'Electric'), ('Mechanical', 'Mechanical'), ('Painting', 'Painting')], max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('working_hours', models.CharField(help_text='e.g., Mon-Fri 9:00-17:00', max_length=50)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
