# Generated by Django 5.2.4 on 2025-07-25 20:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnedMotorcycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
                ('production_year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(2025)])),
                ('engine_type', models.CharField(choices=[('Inline', 'Inline'), ('V', 'V')], max_length=20)),
                ('engine_volume', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('engine_power', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_motorcycle', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
