# Generated by Django 5.2.4 on 2025-08-02 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownedmotorcycle',
            name='engine_type',
            field=models.CharField(choices=[('Inline', 'Inline'), ('V', 'V'), ('Other', 'Other')], max_length=20),
        ),
    ]
