# Generated by Django 5.2.4 on 2025-08-04 18:33

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_ownedmotorcycle_engine_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, error_messages={'unique': 'That phone number is already in use!'}, help_text='Enter your phone number (digits, spaces, hyphens, and parentheses allowed)', max_length=15, null=True, unique=True, validators=[accounts.validators.PhoneNumberValidator()]),
        ),
    ]
