# Generated by Django 5.2.4 on 2025-08-04 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownedmotorcycle',
            name='engine_power',
            field=models.PositiveSmallIntegerField(default=160),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ownedmotorcycle',
            name='engine_volume',
            field=models.PositiveSmallIntegerField(default=1000),
            preserve_default=False,
        ),
    ]
