# Generated by Django 5.2.4 on 2025-08-03 15:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clothing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('make', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
                ('category', models.CharField(choices=[('Jacket', 'Jacket'), ('Pants', 'Pants'), ('Helmet', 'Helmet')], max_length=20)),
                ('fit', models.CharField(choices=[('Slim', 'Slim'), ('Athletic', 'Athletic'), ('Chubby', 'Chubby')], max_length=20)),
                ('style', models.CharField(choices=[('Sport', 'Sport'), ('Touring', 'Touring'), ('Cruiser', 'Cruiser'), ('Off-Road', 'Off-Road')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('image_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
